/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Pet {
  id: number;
  name: string;
  species: string;
}

export interface DB {
  pet: Pet;
}
